FROM node:22 AS deps

WORKDIR /build
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

FROM node:22

WORKDIR /opt/5stack

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    bash \
    containerd \
    dmidecode \
    util-linux \
  && rm -rf /var/lib/apt/lists/*

COPY --from=deps /build/node_modules ./node_modules
COPY . .

CMD [ "yarn", "start:dev" ]
