FROM node:22-alpine AS deps

WORKDIR /build
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

FROM node:22-alpine

WORKDIR /opt/5stack

RUN apk add --no-cache util-linux bash containerd-ctr dmidecode

COPY --from=deps /build/node_modules ./node_modules
COPY . .

CMD [ "yarn", "start:dev" ]