FROM node:24 AS deps

WORKDIR /build
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

FROM node:24

WORKDIR /opt/5stack

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    bash \
    containerd \
    dmidecode \
    util-linux \
  && rm -rf /var/lib/apt/lists/*

# crictl for resources/image-prune.sh; Debian does not package it.
ARG CRICTL_VERSION=v1.37.0
ARG TARGETARCH
RUN curl -fsSL "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${TARGETARCH}.tar.gz" \
  | tar -xz -C /usr/local/bin crictl

COPY --from=deps /build/node_modules ./node_modules
COPY . .

CMD [ "yarn", "start:dev" ]
